<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>OpenAI 开发者论坛 - 最新帖子</title>
    <link>https://community.openai.com</link>
    <description>最新帖子</description>
    <lastBuildDate>Tue, 14 May 2024 03:21:50 GMT</lastBuildDate>
    <item>
      <title>在 API 中宣布 GPT-4o！</title>
      <link>https://community.openai.com/t/announcing-gpt-4o-in-the-api/744700#post_17</link>
      <description><![CDATA[即使是英语也会受益于给定文本的标记数量减少大约 10%。
如果您转到此处并向下滚动，
https://openai.com/index /hello-gpt-4o/
您可以看到一些资源较低的语言的标记化得到了多么显着的改进。
这对这些语言的可用性和翻译任务的后续影响将是巨大的。]]></description>
      <guid>https://community.openai.com/t/announcing-gpt-4o-in-the-api/744700#post_17</guid>
      <pubDate>Tue, 14 May 2024 03:21:03 GMT</pubDate>
    </item>
    <item>
      <title>ChatGPT 4o 语音功能不工作</title>
      <link>https://community.openai.com/t/chatgpt-4o-voice-feature-not-working/744770#post_8</link>
      <description><![CDATA[同样的问题，它只是使用常规的 gpt4。我什至询问 gpt-4o 如何与它对话，它说它在 ios 上不可用，但我可以与它在线聊天，但浏览器版本没有显示该选项。]]></description>
      <guid>https://community.openai.com/t/chatgpt-4o-voice-feature-not-working/744770#post_8</guid>
      <pubDate>Tue, 14 May 2024 03:20:13 GMT</pubDate>
    </item>
    <item>
      <title>如何让聊天机器人根据用户在矢量存储中插入的文件做出响应？</title>
      <link>https://community.openai.com/t/how-to-make-the-chatbot-responde-according-to-the-files-the-user-inserted-in-the-vector-store/744393#post_7</link>
      <description><![CDATA[或更简单地说：在助手中，矢量存储只能通过 AI 可能调用的文件搜索功能访问，并且只能在该端点中访问。
您必须创建自己的基于嵌入的矢量数据库来完成聊天，然后对于您想要自动注入知识的每个输入，在输入上运行嵌入 AI 模型调用（可能还有更多上下文或语言转换）获取输入向量，您可以使用它对所有数据库条目进行详尽的搜索，以人工智能在放入上下文时可以理解的格式返回顶部结果，例如系统消息“您已自动添加了此附加知识满足最近的用户输入...”
然后，它可以是自动的，基于质量阈值，使用语义或手动分块技术，不需要人工智能决定来调用工具或使内部调用和成本加倍，以及您可以比助理更好的所有其他方式.]]></description>
      <guid>https://community.openai.com/t/how-to-make-the-chatbot-responde-according-to-the-files-the-user-inserted-in-the-vector-store/744393#post_7</guid>
      <pubDate>Tue, 14 May 2024 03:13:19 GMT</pubDate>
    </item>
    <item>
      <title>GPT-4o 错误：系统消息中的图像 URL</title>
      <link>https://community.openai.com/t/gpt-4o-error-image-urls-in-system-messages/745769#post_3</link>
      <description><![CDATA[感谢您指出这一点！
我将进一步查看文档，以确保遵循正确的格式。]]></description>
      <guid>https://community.openai.com/t/gpt-4o-error-image-urls-in-system-messages/745769#post_3</guid>
      <pubDate>Tue, 14 May 2024 03:10:58 GMT</pubDate>
    </item>
    </channel>
</rss>