<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>OpenAI 开发者论坛 - 最新帖子</title>
    <link>https://community.openai.com</link>
    <description>最新帖子</description>
    <lastBuildDate>Sat, 06 Jul 2024 21:19:47 GMT</lastBuildDate>
    <item>
      <title>文件上传并在助手 (v2) 对话中对其进行操作</title>
      <link>https://community.openai.com/t/file-upload-and-acting-on-it-in-an-assistant-v2-conversation/856370#post_10</link>
      <description><![CDATA[这看起来更像是 RAG 设置，而不是我在这里做的（我使用的是自己的 RAG 设置）
顺便说一句：添加“file_search”是我尝试让它工作的众多选项之一，但我认为我在那里混淆了概念。所以我暂时将其删除（不会改变与问题相关的任何事情。]]></description>
      <guid>https://community.openai.com/t/file-upload-and-acting-on-it-in-an-assistant-v2-conversation/856370#post_10</guid>
      <pubDate>Sat, 06 Jul 2024 21:19:17 GMT</pubDate>
    </item>
    <item>
      <title>不适用于注重隐私的浏览器</title>
      <link>https://community.openai.com/t/doesnt-work-in-privacy-friendly-browsers/856441#post_1</link>
      <description><![CDATA[当我使用 librewolf（强化版 Firefox 浏览器）时，它经常会进入冻结状态并超时。也许它认为我是机器人。看看这个 3 倍加速的 gif。

加分项：当您多次按下 Enter 键时，它会启动多个提示，阻止下一个提示运行，或者您只会收到“出现问题”错误。
当我使用原版 Chromium 时，这种情况从未发生过。我知道你必须采取某些保护措施来防范机器人，但为什么要对付费用户采取这些保护措施呢？如果机器人过度使用付费账户，只需给它们设置每日消息上限即可。]]></description>
      <guid>https://community.openai.com/t/doesnt-work-in-privacy-friendly-browsers/856441#post_1</guid>
      <pubDate>Sat, 06 Jul 2024 21:15:17 GMT</pubDate>
    </item>
    <item>
      <title>文件上传并在助手 (v2) 对话中对其进行操作</title>
      <link>https://community.openai.com/t/file-upload-and-acting-on-it-in-an-assistant-v2-conversation/856370#post_9</link>
      <description><![CDATA[请参阅快速入门指南中的步骤 3，以更新助手的 tool_resources]]></description>
      <guid>https://community.openai.com/t/file-upload-and-acting-on-it-in-an-assistant-v2-conversation/856370#post_9</guid>
      <pubDate>Sat, 06 Jul 2024 21:10:33 GMT</pubDate>
    </item>
    <item>
      <title>文件上传并在助手 (v2) 对话中对其进行操作</title>
      <link>https://community.openai.com/t/file-upload-and-acting-on-it-in-an-assistant-v2-conversation/856370#post_8</link>
      <description><![CDATA[我看过一些例子，但我认为这只是用于在创建时初始上传文件（我不需要）。
在我的上下文中，上传到 https://api.openai.com/v1/files 需要什么 tool_resource 设置？]]></description>
      <guid>https://community.openai.com/t/file-upload-and-acting-on-it-in-an-assistant-v2-conversation/856370#post_8</guid>
      <pubDate>Sat, 06 Jul 2024 21:06:52 GMT</pubDate>
    </item>
    <item>
      <title>文件上传并在助手 (v2) 对话中对其进行操作</title>
      <link>https://community.openai.com/t/file-upload-and-acting-on-it-in-an-assistant-v2-conversation/856370#post_7</link>
      <description><![CDATA[做了一些调试：
这是上传的文件（file-id）：
2024-07-06T22:54:37.632118+0200 [TRACE] [run] 文件 ID：“file-CDlwWHavbyT0HMgXoFiKnDKM”

这是文件列表的摘录。因此文件确实存在（列表中的第一个）：
文件列表：
SyncPage[FileObject](data=[FileObject(id=&#39;file-CDlwWHavbyT0HMgXoFiKnDKM&#39;, bytes=29568, created_at=1720299278, filename=&#39;uploaded_file&#39;, object=&#39;file&#39;, purpose=&#39;assistants&#39;, status=&#39;processed&#39;, status_details=None), FileObject(id=&#39;file-xB8Rr9sioXbfv0bB91Crq9Q2&#39;, bytes=29568, created_at=1720299104, filename=&#39;uploaded_file&#39;, object=&#39;file&#39;, purpose=&#39;assistants&#39;, status=&#39;processed&#39;, status_details=None), FileObject(id=&#39;file-6zwgCDX8EAOwuk1KQIcIn8k9&#39;, bytes=29568, created_at=1720298992, filename=&#39;uploaded_file&#39;, object=&#39;file&#39;, purpose=&#39;assistants&#39;, status=&#39;processed&#39;, status_details=None), FileObject(id=&#39;file-Rt2z4Uq6hri5tBOAkgBJMcnI&#39;, bytes=29568, created_at=1720298889, filename=&#39;uploaded_file&#39;, object=&#39;file&#39;, purpose=&#39;assistants&#39;, status=&#39;processed&#39;, status_details=None), ... 
], object=&#39;list&#39;, has_more=False)

但使用以下方法检查是否存在：
 def check_file_exists(self, file_id):
try:
file_list = self.client.files.list()
logger.trace(f&quot;文件列表：{file_list}&quot;)
if any(file.id == file_id for file in file_list):
return True
else:
logger.error(f&quot;ID 为 {file_id} 的文件不存在。&quot;)
return False
except Exception as e:
logger.exception(f&quot;检查文件存在性时出错：{e}&quot;)
return False

表示不存在...令人困惑...
我的存在性测试有误吗？]]></description>
      <guid>https://community.openai.com/t/file-upload-and-acting-on-it-in-an-assistant-v2-conversation/856370#post_7</guid>
      <pubDate>Sat, 06 Jul 2024 21:04:27 GMT</pubDate>
    </item>
    <item>
      <title>文件上传并在助手 (v2) 对话中对其进行操作</title>
      <link>https://community.openai.com/t/file-upload-and-acting-on-it-in-an-assistant-v2-conversation/856370#post_6</link>
      <description><![CDATA[当您创建助手时，您包含了“file_search”工具，但我没有看到“tool_resources”条目。类似以下内容：
 tool_resources={
&quot;file_search&quot;: {
&quot;vector_store_ids&quot;: [theVectorIdContainingFileIdsUsed]
}
}

]]></description>
      <guid>https://community.openai.com/t/file-upload-and-acting-on-it-in-an-assistant-v2-conversation/856370#post_6</guid>
      <pubDate>Sat, 06 Jul 2024 21:04:19 GMT</pubDate>
    </item>
    <item>
      <title>ChatGPT 有时会在同一会话中重复使用工具 ID</title>
      <link>https://community.openai.com/t/chatgpt-occasionally-reuses-tool-ids-in-the-same-session/577207#post_3</link>
      <description><![CDATA[我们在使用 Gpt-4o 时遇到了同样的问题。
您找到解决方法了吗？]]></description>
      <guid>https://community.openai.com/t/chatgpt-occasionally-reuses-tool-ids-in-the-same-session/577207#post_3</guid>
      <pubDate>Sat, 06 Jul 2024 20:17:11 GMT</pubDate>
    </item>
    <item>
      <title>文件上传并在助手 (v2) 对话中对其进行操作</title>
      <link>https://community.openai.com/t/file-upload-and-acting-on-it-in-an-assistant-v2-conversation/856370#post_5</link>
      <description><![CDATA[]]></description>
      <guid>https://community.openai.com/t/file-upload-and-acting-on-it-in-an-assistant-v2-conversation/856370#post_5</guid>
      <pubDate>Sat, 06 Jul 2024 20:13:12 GMT</pubDate>
    </item>
    <item>
      <title>文件上传并在助手 (v2) 对话中对其进行操作</title>
      <link>https://community.openai.com/t/file-upload-and-acting-on-it-in-an-assistant-v2-conversation/856370#post_4</link>
      <description><![CDATA[使用 curl 检查上传是否成功：
{
&quot;object&quot;: &quot;file&quot;,
&quot;id&quot;: &quot;file-0fa3WOWpk1R7rrLaiBOQVlR1&quot;,
&quot;purpose&quot;: &quot;assistants&quot;,
&quot;filename&quot;: &quot;uploaded_file&quot;,
&quot;bytes&quot;: 29568,
&quot;created_at&quot;: 1720294914,
&quot;status&quot;: &quot;processed&quot;,
&quot;status_details&quot;: null
}```]]></description>
      <guid>https://community.openai.com/t/file-upload-and-acting-on-it-in-an-assistant-v2-conversation/856370#post_4</guid>
      <pubDate>Sat, 06 Jul 2024 19:49:07 GMT</pubDate>
    </item>
    <item>
      <title>文件上传并在助手 (v2) 对话中对其进行操作</title>
      <link>https://community.openai.com/t/file-upload-and-acting-on-it-in-an-assistant-v2-conversation/856370#post_3</link>
      <description><![CDATA[我从代理创建中删除了 Org-id（也从 .env 文件中删除了），并仔细检查了是否使用了相同的 API 密钥。仍然是同样的错误
我注意到一件事：Flask 在 404 之后添加了一个 500 错误（？）
INFO - httpx - HTTP 请求：POST https://api.openai.com/v1/threads/thread_E5iY1r5u7cZqsJ34Dt509SJF/messages“HTTP/1.1 404 未找到”
INFO - werkzeug - 127.0.0.1 - - [06/Jul/2024 21:41:54]“POST /api/message HTTP/1.1”500 -
]]></description>
      <guid>https://community.openai.com/t/file-upload-and-acting-on-it-in-an-assistant-v2-conversation/856370#post_3</guid>
      <pubDate>Sat, 06 Jul 2024 19:46:14 GMT</pubDate>
    </item>
    <item>
      <title>我可以在不使用提供的 SDK 的情况下调用 OpenAI Assistants API 吗？</title>
      <link>https://community.openai.com/t/can-i-call-openai-assistants-apis-without-using-the-provided-sdks/856249#post_3</link>
      <description><![CDATA[是的，有官方 SDK、非官方 SDKS 和老式的 REST 请求。甚至还有像整个 OpenAI API 文档中一样发出请求的示例。
curl https://api.openai.com/v1/models \
-H &quot;Authorization: Bearer $OPENAI_API_KEY&quot; \
-H &quot;OpenAI-Organization: YOUR_ORG_ID&quot; \
-H &quot;OpenAI-Project: $PROJECT_ID&quot;
]]></description>
      <guid>https://community.openai.com/t/can-i-call-openai-assistants-apis-without-using-the-provided-sdks/856249#post_3</guid>
      <pubDate>Sat, 06 Jul 2024 19:42:07 GMT</pubDate>
    </item>
    <item>
      <title>执行 API 请求时出现随机 OpenSSL 错误，似乎与 IP 地址有关</title>
      <link>https://community.openai.com/t/random-openssl-errors-when-doing-api-requests-appears-to-be-ip-address-related/103850#post_5</link>
      <description><![CDATA[我现在每天都遇到同样的问题，多次请求都这样。没有代码，也没有更改服务器设置。
OpenSSL SSL_read：错误：0A0003FC：SSL 例程：：sslv3 警报错误记录 mac，errno 0 - 代码：56]]></description>
      <guid>https://community.openai.com/t/random-openssl-errors-when-doing-api-requests-appears-to-be-ip-address-related/103850#post_5</guid>
      <pubDate>Sat, 06 Jul 2024 19:35:27 GMT</pubDate>
    </item>
    <item>
      <title>文件上传并在助手 (v2) 对话中对其进行操作</title>
      <link>https://community.openai.com/t/file-upload-and-acting-on-it-in-an-assistant-v2-conversation/856370#post_2</link>
      <description><![CDATA[您遇到的问题可能与项目范围有关。
确保您发出的每个请求都使用相同的 API 密钥，除非您使用的组织 ID 不是您自己的或您无法设置为默认值，否则不要在标头中发送组织或项目，也不要让它们从环境变量中发送，否则 SDK 无论如何都会抓取它们。]]></description>
      <guid>https://community.openai.com/t/file-upload-and-acting-on-it-in-an-assistant-v2-conversation/856370#post_2</guid>
      <pubDate>Sat, 06 Jul 2024 19:35:02 GMT</pubDate>
    </item>
    <item>
      <title>知识如何发挥作用，对于操作、API 也是如此，我的意思是通过示例 + 我的示例</title>
      <link>https://community.openai.com/t/how-does-knowledge-work-and-the-same-for-actions-api-i-mean-with-examples-my-example/835775#post_9</link>
      <description><![CDATA[我已向您发送了一条私信。请随时联系我，我会密切关注我的留言板活动。]]></description>
      <guid>https://community.openai.com/t/how-does-knowledge-work-and-the-same-for-actions-api-i-mean-with-examples-my-example/835775#post_9</guid>
      <pubDate>Sat, 06 Jul 2024 19:34:55 GMT</pubDate>
    </item>
    <item>
      <title>公开请求 NSFW 支持：使用案例 + 举手支持！</title>
      <link>https://community.openai.com/t/open-plea-for-nsfw-support-use-case-raise-your-hand-to-support/850872?page=2#post_27</link>
      <description><![CDATA[为 NSFW 群体举手，将文本作为图像和视频]]></description>
      <guid>https://community.openai.com/t/open-plea-for-nsfw-support-use-case-raise-your-hand-to-support/850872?page=2#post_27</guid>
      <pubDate>Sat, 06 Jul 2024 19:33:22 GMT</pubDate>
    </item>
    </channel>
</rss>